Feature school
chandure-manjiri/mybatis pull request #1
Opened 2024-03-13 06:15 UTC by chandure-manjiri

only entities & controllers are there

2024-03-13 11:54 UTC, pratik-techprescient requested changes

2024-03-13 11:54 UTC, pratik-techprescient commented on src/main/java/mybatis/com/mybatis/Controller/StudentController.java
> +    public ResponseEntity<StudentEntity> getStudentWithSubjectList(@PathVariable (name = "id") Integer id){
I think we should just return the list of subjects opted by the student as the response. The API URL/Path is requesting subject info and not a student.
Or we can return a DTO that has basic student info like (id, name) and a list of subjects as attributes.

Let's implement the 2nd approach in the DTO PR

2024-03-13 11:54 UTC, pratik-techprescient commented on src/main/java/mybatis/com/mybatis/Entity/StudentEntity.java
> +    private List<SubjectEntity> subjectEntityList;
```suggestion
    private List<SubjectEntity> subjectEntities/subjects
```
Wherever possible use plural instead of adding list as a suffix.

2024-03-13 11:54 UTC, pratik-techprescient commented on src/main/java/mybatis/com/mybatis/Entity/SubjectEntity.java
> +    private TeacherEntity teacherEntity;
For myBatis, associations can be added based on the use case. Like JPA, we don't have to add a bidirectional mapping every time.

2024-03-13 11:54 UTC, pratik-techprescient commented on src/main/java/mybatis/com/mybatis/Repository/StudentRepository.java
> +    List<StudentEntity> getStudents();
```suggestion
    List<StudentEntity> findAllStudents();
```
Since repos communicate with the database to find/update/save the records the method names should convey that.
We can follow a similar naming convention as JPA.

2024-03-13 11:54 UTC, pratik-techprescient commented on src/main/java/mybatis/com/mybatis/Repository/StudentRepository.java
> +    void assignSubjectsToStudent(@Param("id")Integer id, @Param("subjectEntityList")List<SubjectEntity> subjectEntityList);
```suggestion
    void assignSubjectsToStudent(@Param("id")Integer id, @Param("subjectEntityList")List<SubjectEntity> subjectEntities);
```

2024-03-13 11:54 UTC, pratik-techprescient commented on src/main/resources/mapper/StudentMapper.xml
> +    <insert id="assignSubjectsToStudent" useGeneratedKeys="true"
mention parameter information

2024-03-13 11:54 UTC, pratik-techprescient commented on src/main/resources/mapper/TeacherMapper.xml
> +                    column="id" select="selectSubjectByTeacherId"/>
TBD

2024-03-14 07:13 UTC, chandure-manjiri commented on src/main/resources/mapper/TeacherMapper.xml
> +                    column="id" select="selectSubjectByTeacherId"/>
sorry but didn't get what is TBD?

2024-03-14 07:46 UTC, pratik-techprescient commented on src/main/java/mybatis/com/mybatis/Entity/SubjectEntity.java
> +    private TeacherEntity teacherEntity;
Ignore this for now, will discuss this during DTO PR.

2024-03-14 07:57 UTC, chandure-manjiri commented on src/main/java/mybatis/com/mybatis/Entity/StudentEntity.java
> +    private List<SubjectEntity> subjectEntityList;
done

2024-03-14 07:57 UTC, chandure-manjiri commented on src/main/java/mybatis/com/mybatis/Entity/SubjectEntity.java
> +    private TeacherEntity teacherEntity;
ok

2024-03-14 07:58 UTC, chandure-manjiri commented on src/main/java/mybatis/com/mybatis/Repository/StudentRepository.java
> +    List<StudentEntity> getStudents();
done

2024-03-14 07:58 UTC, chandure-manjiri commented on src/main/java/mybatis/com/mybatis/Repository/StudentRepository.java
> +    void assignSubjectsToStudent(@Param("id")Integer id, @Param("subjectEntityList")List<SubjectEntity> subjectEntityList);
done

2024-03-14 08:48 UTC, chandure-manjiri commented on src/main/resources/mapper/StudentMapper.xml
> +    <insert id="assignSubjectsToStudent" useGeneratedKeys="true"
done

2024-03-14 08:48 UTC, chandure-manjiri commented on src/main/java/mybatis/com/mybatis/Controller/StudentController.java
> +    public ResponseEntity<StudentEntity> getStudentWithSubjectList(@PathVariable (name = "id") Integer id){
ok

2024-03-14 11:11 UTC, pratik-techprescient approved these changes

2024-03-18 06:35 UTC, merged